#!/usr/bin/env bash

##################
# dotFile majixs #
##################
alias dotFiles='/usr/bin/git --git-dir=${HOME}/.dotFiles/ --work-tree=${HOME}'
alias dt=dotFiles

###########################################
# list files with folder/synlink demarker #
###########################################
if [[ -n ${GNU_STYLE_LS} ]]; then
	alias ls='ls --color -F'
else
    alias ls='ls -F'
fi

#############
# shortcuts #
#############
alias cl='clear'

# defaults read/write
#####################
alias dr="defaults read"
alias dw="defaults write"

# git shortcuts
###############
alias gp="git pull --recurse-submodules --tags"
alias gck="git cherry-pick"
alias tigf="tig --first-parent"
alias tigs="tig --show-signature"

##########################################
# some helpful probes to open UI Editors #
##########################################
if [[ -d /Applications/MacDown.app ]]; then
    alias openm='open -a /Applications/MacDown.app'
fi
if [[ -d /Applications/Xcode.app ]]; then
    alias openx='open -a /Applications/Xcode.app'
fi
if [[ -d /Applications/MacVim.app ]]; then
    alias openv='open -a /Applications/MacVim.app'
fi
if [[ -d /Applications/BBEdit.app ]]; then
    alias openb='open -a /Applications/BBEdit.app'
fi

#########
# tools #
#########

# flush DS cache
#################
alias flush="dscacheutil -flushcache && killall -HUP mDNSResponder"

# cleanup LaunchServices "Open With" menu
#########################################
alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder Dock"
