#!/usr/bin/env bash

######################
# set color terminal #
######################
if ls --color > /dev/null 2>&1; then # GNU `ls`
    export GNU_STYLE_LS=1
else
    export CLICOLOR=1
fi

if [[ ! -v ${CLICOLOR} ]] ; then
    export LSCOLORS="gxfxcxdxbxegedabagacad"
fi

##########################
# set HISTORY properties #
##########################
shopt -s histappend
export HISTCONTROL=ignorespace:erasedups
export HISTSIZE=-1
export HISTFILESIZE=-1

##############################
# virtualenvwrapper settings #
##############################
export VIRTUALENVWRAPPER_PYTHON=$(brew --prefix)/bin/python3
export WORKON_HOME=~/projects/venv
export VIRTUALENVWRAPPER_VIRTUALENV=$(brew --prefix)/bin/virtualenv
source $(brew --prefix)/bin/virtualenvwrapper.sh

##################
# other settings #
##################
export VIMRUNTIME=$(brew --prefix)'/share/vim/vim91'
