#!/usr/bin/env bash

#######################
# set PATH # to glory #
#######################
BREW_BIN="$(/opt/brew/bin/brew --prefix)/bin"
BREW_SBIN="$(/opt/brew/bin/brew --prefix)/sbin"
LOCAL_BIN="/usr/local/bin"
LOCAL_SBIN="/usr/local/sbin"
MY_LOCAL_BIN="${HOME}/usr/bin"
PATH="${BREW_BIN}:${BREW_SBIN}:${LOCAL_BIN}:${LOCAL_SBIN}:${MY_LOCAL_BIN}:${PATH}"

# de-dup path entries
#####################
export PATH=$(printf %s "${PATH}" | awk -v RS=: '{ if (!arr[$0]++) {printf("%s%s",!ln++?"":":",$0)}}')
