#!/usr/bin/env bash

#######################
# set PATH # to glory #
#######################
if [ -f '/opt/homebrew/bin/brew' ]; then
    BREW_BOOTSTRAP_EXEC='/opt/homebrew/bin/brew'
elif [ -f '/opt/brew/bin/brew' ]; then
    BREW_BOOTSTRAP_EXEC='/opt/brew/bin/brew'
fi
BREW_BIN="$(${BREW_BOOTSTRAP_EXEC} --prefix)/bin"
BREW_SBIN="$(${BREW_BOOTSTRAP_EXEC} --prefix)/sbin"
LOCAL_BIN="/usr/local/bin"
LOCAL_SBIN="/usr/local/sbin"
MY_LOCAL_BIN="${HOME}/usr/bin"
PATH="${BREW_BIN}:${BREW_SBIN}:${LOCAL_BIN}:${LOCAL_SBIN}:${MY_LOCAL_BIN}:${PATH}"

# de-dup path entries
#####################
export PATH=$(printf %s "${PATH}" | awk -v RS=: '{ if (!arr[$0]++) {printf("%s%s",!ln++?"":":",$0)}}')
